version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .
            pip install black flake8

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "setup.py" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            black --check ./buildmap

      - setup_remote_docker:
          docker_layer_caching: true

      - run: 
          name: build docker image
          command: |
            docker build -t russss/buildmap:$CIRCLE_BUILD_NUM -t russss/buildmap .
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker push russss/buildmap:$CIRCLE_BUILD_NUM
            docker push russss/buildmap
